# _*_ mode: ruby _*_
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # the vuln machine (target subnet)
  config.vm.define "target" do |target|
    target.vm.box = "ubuntu/xenial64" 
    target.vm.hostname = "target"
    target.vm.synced_folder ".", "/vagrant", disabled: true
    target.vm.network "private_network", ip: "10.10.10.10/24", virtualbox__intnet: "internal", nic_type: "virtio"
    target.vm.provision "shell", run: "always", inline: "sudo ip route del default"
    target.vm.provision "shell", run: "always", inline: "sudo ip route add default via 10.10.10.254"

    target.vm.provider "virtualbox" do |vb|
      vb.name = "target"
      vb.gui = false
      vb.memory = "512"
    end
  end

  # the router 0 (between target subnet and router1)
  config.vm.define "router0"  do |router0|
    router0.vm.box = "debian/contrib-jessie64" 
    router0.vm.hostname = "router0"
    router0.vm.synced_folder "output/", "/tmp/", disabled: true
    router0.vm.network "private_network", ip: "10.10.10.254/24", virtualbox__intnet: "internal", nic_type: "virtio"
    router0.vm.network "private_network", ip: "10.20.10.254/24", virtualbox__intnet: "routers", nic_type: "virtio"

    router0.vm.provision "shell", run: "always", inline: "ip route add 172.16.0.0/24 via 10.20.10.253"
    router0.vm.provision "shell", run: "always", inline: "sysctl -w net.ipv4.ip_forward=1"
    router0.vm.provision "shell", run: "always", inline: "echo [Router] Configuration done!"

    router0.vm.provider "virtualbox" do |vb|
      vb.name = "router0"
      vb.gui = false
      vb.memory = "512"
      # https://www.virtualbox.org/wiki/Network_tips
      vb.customize ['modifyvm', :id, '--nictrace2', 'on']
      vb.customize ['modifyvm', :id, '--nictracefile2', 'router0_output.pcap']
    end
  end

  # the router 1 (between attacker and router0)
  config.vm.define "router1"  do |router1|
    router1.vm.box = "debian/jessie64"
    router1.vm.hostname = "router1" 
    router1.vm.synced_folder ".", "/vagrant", disabled: true
    router1.vm.network "private_network", ip: "10.20.10.253/24", virtualbox__intnet: "routers", nic_type: "virtio"
    router1.vm.network "private_network", ip: "172.16.0.254/24", virtualbox__intnet: "external", nic_type: "virtio"

    router1.vm.provision "shell", run: "always", inline: "ip route add 10.10.10.0/24 via 10.20.10.254"
    router1.vm.provision "shell", run: "always", inline: "sysctl -w net.ipv4.ip_forward=1"
    # IPTABLES NAT
    # eth0 - Vagrant
    # eth1 - 10.20.10.253
    # eth2 - 172.16.0.254
    router1.vm.provision "shell", run: "always", inline: "iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE"
    router1.vm.provision "shell", run: "always", inline: "iptables -A FORWARD -i eth1 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT"
    router1.vm.provision "shell", run: "always", inline: "iptables -A FORWARD -i eth2 -o eth1 -j ACCEPT"
    

    # NAT configuration


    router1.vm.provision "shell", inline: "echo [Router] Configuration done!"

    router1.vm.provider "virtualbox" do |vb|
      vb.name = "router1"
      vb.gui = false
      vb.memory = "512"
    end
  end

  # the attacker machine
  config.vm.define "attacker" do |attacker|
    attacker.vm.box = "kalilinux/rolling" 
    attacker.vm.hostname = "attacker" 
    attacker.vm.synced_folder ".", "/vagrant", disabled: true
    attacker.vm.network "private_network", ip: "172.16.0.2/24", virtualbox__intnet: "external"
    
    attacker.vm.provision "shell", run: "always", inline: "ip route add 10.10.10.0/24 via 172.16.0.254"

    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "attacker" 
      vb.memory = "1024"
    end
  end


end
